# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: avchWj9f3vaEma3Fn4FP

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: avchWj9f3vaEma3Fn4FP
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  desilvaphillips.com:
    env:
      db_password: pX6Sa4NyKjLceuXgjUxz
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "1HK#7N4O@2wWcd#cn-j7eezI^YsCGtb?H!haaz?k8.&tK<5!Od,>5Zso6JJZy1qD"
      secure_auth_key: "[XG5T;E=1)qWP]e6xe]b@P6KWr2tP*b>-C`GbyRJR!#,8^Xy=r*:OvFB|^;sOAu<"
      logged_in_key: "{#@34%zsZA4iv|c+TfTr:USA:J/e!^Hd|}8B8ALiq@Ai0Cb3bW_@95Xp3AynRM7-"
      nonce_key: "f.=Hl+&uZ?0Yz-2O+7h6Kuow@N6fBy@f-J+qha`ZdSH9]|mw7iXz6CVDhT?^x{5`"
      auth_salt: "[o?9b3yEf_fw2rXiEWvTL%j}q53e^F$NFyn0C:O,c6cLOJ=b>bT.?fq^,P$q4&{|"
      secure_auth_salt: "C.ELXU{:FOvr.{4TE]oBLxuFdN@P6@$]6M-8$S71,6.lq6`MG`:q&}mHL.|#z/>k"
      logged_in_salt: "]GhZ[V1@4OuIIZz2a,B;/eD_KB1}4*wdNVIK7?/j.nH{/JyE;TDVU8]KLbwviNTw"
      nonce_salt: "b^=e54J;4$0{X,lO6qqnNPH28{M(f`Yrdhfl}rdh%mT1kIv-B`W[iv;dD[>`m;Iy"
